### ISSUE TITLE
Homework Feedback - HTML/CSS - week 1

### ISSUE THREAD

**Issue by susaneme** [priyankapandey13/hyf-homework#1]
First of all, your cv looks professional, you could start using it for real 🙃 
I like the way you played with opening and closing text throughout your content 👩‍💻 , also the effect behind of your picture, and in general the way you organized your content, specially that the background is aligned with your hand like you are standing in a wall! SUPER COOL! You used semantic tags, nice! Another thing that you did that is super useful is to comment the code, like `		<!-- block starts here -->` or  `<!-- block ends here -->`  , your future teammates will love that, it will make their life easier when maintaining some development that you started! Congratulations!!!!🥇 
You did a great job, and I have just few observations: try to make your code as readable as possible, when I say that I mean remove spaces or empty lines, like leaving it concise and also and most import use indentation so we know each block of code belong to each respective parent, for both HTML and CSS. Formatting is not something that affects or code, is just best practice 😄 . In the ` skills section` I didnt understand this part of the code in each `li` `<li>Adobe creative cloud		<aside><span></span></aside></li>`, I dont think it is semantic, and also necessary 🙃 . You styles are consise in general, i would suggest them to be more organized and formatted though. 

WELL DONE! 🌷

**Comment by priyankapandey13** [comment]
Thank you Susane for your lovely feedback:sparkling_heart:. I will surely work on the suggestions in upcoming projects. Just wanted to confirm one thing in `<li>Adobe creative cloud <aside><span></span></aside></li>` i used aside and span for the progress bar but must forget to differentiate the progress in each skill:sweat_smile:. Can you please tell me what would be the best practice to do that if i want to use only semantic html in this?  That would be very helpful. Thank you:blush:

**Comment by susaneme** [comment]
I was looking for any semantic elements to achieve that, and I came across this tag `<progress></progress>` tag, that seems quite simple to use, here [W3Schools HTML 5 progress](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_progress). But you could also try examples like [this](http://jsfiddle.net/cwZSW/1406/) where you use `div` and some few styling as well 😸

**Comment by priyankapandey13** [comment]
Thank you very much for the feedback, will definitely use this 😊
