### ISSUE TITLE
Does this code work?

### ISSUE THREAD

**Issue by aleksd-dfds** [priyankapandey13/hyf-homework#10]
https://github.com/priyankapandey13/hyf-homework/blob/18ebb6b87a9f316937b844547ffa65bfbdec01c1/javascript/javascript2/week2/main.js#L35

Doesn't look like you ran it. It has syntax errors.

**Comment by priyankapandey13** [comment]
It had a bug but i fixed it now.

**Comment by aleksd-dfds** [comment]
When you say "fixed it now", there should be a PR or a commit with that fix ;)
