### ISSUE TITLE
Homework feedback - JS1- week1

### ISSUE THREAD

**Issue by Swapna-Sahu** [priyankapandey13/hyf-homework#2]
Hi,
Great work 👍 . Good to see that you have used const and let. 
Try to use backticks and $ for variable.
I have only one comment for you in your task:
Task - Housey pricey 
You do not need to use two times if . you can avoid using in line 47. Instead you can write like this: 
if(housePrice === housegivenPrice)
{
    result2 = 'You are paying ' + housePrice + ' for your house which is just perfect.';
    console.log(result2)
}
else if(housePrice > housegivenPrice){
    result2 = 'You are paying ' + housePrice + ' for your house which is cheaper for a house like this you should buy it.';
    console.log(result2)
}
else{
    result2 = 'You are paying ' + housePrice + ' for your house it is expensive do not buy it.';
    console.log(result2)
}

All looks good to me . After updating push you file to github and then close the issue. 
Change your repo setting if you want to show htmlpreview.
Keep coding 👍

**Comment by priyankapandey13** [comment]
Thank You for your comments, i am closing this issue now
