### ISSUE TITLE
Homework Feedback JS1-Week2

### ISSUE THREAD

**Issue by ovbm** [priyankapandey13/hyf-homework#3]
Hi Priyanka, 

Thanks for your homework, here's my feedback:
One thing up front, it would make it a bit easier to review if most of the code wasn't commented out. Ideally comments should only be used for your remarks. What you could do is only comment out the function calls or the console.logs. Just an idea. 
 
getFullname
Great job, one small tip, you can write:
`useFormalName.checked == true` simply as `useFormalName.checked` and `useFormalName.checked != true` as `!useFormalName.checked`

getEventWeekday
Great use of the modulo operator.

weather
instead of reurning an errror for temperatures above 22 deg, it would have been better to suggest a default option for hot weather.

students
`class07Students.push("newStudentName");` here you are adding the string literal and not the value of the newStudentName variable. Also, you forgot to add the functionality that allows for the "queen" to always be added regardless of the amount of people on the list. Would be great if you could try to add that. 

Good job overall! 🌟

Olivier

**Comment by priyankapandey13** [comment]
Hi, thanks for the detailed review.

**Comment by priyankapandey13** [comment]
Hi, i have updated the code as per your suggestion. Can you please go through my code. i am also facing one problem with the "Event Application" code. It works totally fine as how it is, but it skips Sunday if i input the value by submitting textbox value. Thanks in advance
