### ISSUE TITLE
Homework Feedback JS1-week3

### ISSUE THREAD

**Issue by Swapna-Sahu** [priyankapandey13/hyf-homework#4]
Good work 👍 . Sorry I was not posted .

I have few comments in your task.

Item array removal Task -
It is not removing the name but the task was for using method (push, pop, shift, slice).
Task was removing random name using random method. Here, you are choosing the position and removing it. For removing random name from the array either you use for loop inside If statement or you can just check the index of the element which is matching then slice it.

Series Task -
Everything looks good but I don’t know what you have calculated . It will be good if you could have breakdown the calculation 
totalEach = (seriesDurations[i].days)*0.00273790926 + (seriesDurations[i].hours)*0.000114079553 + (seriesDurations[i].minutes)*0.000114079553/60 ;
 favSong Task - 
getSongByTitle is not working. It should print full song object.

**Comment by priyankapandey13** [comment]
Thanks Swapna, i did all your suggested updates.
