### ISSUE TITLE
Splitting unnecessary

### ISSUE THREAD

**Issue by aleks-hyf** [priyankapandey13/hyf-homework#5]
https://github.com/priyankapandey13/hyf-homework/blob/6b34b66d5109bd6cce45f7bbcfbc57727db7a11f/javascript/javascript2/week1/main.js#L16

`danishWords[i].split("").length;` is basically the same as
` danishWords[i].length;`

**Comment by priyankapandey13** [comment]
Okay, Thanks for clarification.
