### ISSUE TITLE
Sorting out of place

### ISSUE THREAD

**Issue by aleks-hyf** [priyankapandey13/hyf-homework#7]
https://github.com/priyankapandey13/hyf-homework/blob/6b34b66d5109bd6cce45f7bbcfbc57727db7a11f/javascript/javascript2/week1/main.js#L39

Sorting is unnecessary and actually incorrect here => Average needs only sum and division.

**Comment by priyankapandey13** [comment]
Thank you so much for your detailed comments. I have updated the js file keeping the comments in mind please have a look.
