### ISSUE TITLE
assignment incomplete

### ISSUE THREAD

**Issue by aleks-hyf** [priyankapandey13/hyf-homework#8]
https://github.com/priyankapandey13/hyf-homework/blob/6b34b66d5109bd6cce45f7bbcfbc57727db7a11f/javascript/javascript2/week1/main.js#L48

Where's the function `getMedian`, etc? Something is unfinished here.

**Comment by priyankapandey13** [comment]
Thank you so much for your detailed comments. I have updated the js file keeping the comments in mind please have a look.

**Comment by aleks-hyf** [comment]
Not sure your current solution solves the problem. The function getAverage doesn't actually get the average, and there's no attempt to get the median. Check with your classmates or get help if you're not sure how to do it.
